### ISSUE TITLE
Give Sponsors and partners links

### ISSUE THREAD

**Issue by Developerayo** [Developerayo/unstack.africa#21]

**Comment by lumie31** [comment]
Sorry this is coming late but I don't seem to understand this issue

**Comment by Developerayo** [comment]
Oh this!
When the sponsor's logos are clicked, it should target into a new window for their website

**Comment by lumie31** [comment]
Should I still work on this or has it been done?

**Comment by Developerayo** [comment]
It hasn't been done,

But leave it commented out in homepage.js when pushing

**Comment by Developerayo** [comment]
Chief! Any update on this issue?

**Comment by lumie31** [comment]
This has been done and the PR raised. The sponsors' section is also still commented out in homepage.js as suggested
