### ISSUE TITLE
New Sponsors

### ISSUE THREAD

**Issue by Developerayo** [Developerayo/unstack.africa#30]
Hey, @lumie31 Can you add these logos under the bronze sponsors section?

<img width="486" alt="Screenshot 2020-10-25 at 6 33 43 PM" src="https://user-images.githubusercontent.com/20538832/97114458-dbc4c500-16f0-11eb-8b52-94963f49c9d7.png">

Slack (
![image](https://user-images.githubusercontent.com/20538832/97114562-7de4ad00-16f1-11eb-950f-1adaeaf13364.png)
)

Which is Opinionated React & Slack

## Target URL
https://opinionatedreact.com/
http://slack.com/

Can this be up tonight?

**Comment by lumie31** [comment]
This issue has been attended to. However, the `Sponsors` component is still commented out. 

To view the changes made, you'd have to uncomment the `Sponsors` component in the `Homepage` component

**Comment by Developerayo** [comment]
Yes, I'm aware, will pull and test.
